# Generated by Django 3.1.7 on 2022-01-19 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secure254app', '0002_auto_20220119_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='occurence_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
