# Generated by Django 3.1.7 on 2022-01-22 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure254app', '0003_report_occurence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='occurence_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
