# Generated by Django 4.0.4 on 2022-09-23 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure254app', '0007_auto_20220122_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='occurence_date',
            field=models.DateField(default=datetime.date(2022, 9, 23)),
        ),
    ]
